application: ikwimbon-site
version: v20161130

runtime: python27
api_version: 1
threadsafe: true
skip_files:
- (^node_modules/.*)
- (^.git/.*)

handlers:

- url: /static/images/(.*)
  static_files: static/images/\1
  expiration: "1d"
  upload: static/images/(.*)
  secure: always

- url: /(.*)
  script: main.app
  secure: always 

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest